name: gwt
description: "Gym weight tracker app"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_messaging: ^14.9.2
  cloud_firestore: ^4.17.3
  firebase_analytics: ^10.10.5
  firebase_crashlytics: ^3.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true